name: Post Daily Menus to Telegram

on:
  schedule:
    - cron: "00 7 * * 1-5"

  workflow_dispatch: # allows manual run

jobs:
  post-menus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: Run diet bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CHANNEL_ID: ${{ secrets.VEGAN_CHANNEL_ID }}
        run: |
          uv run app.py

      - name: Run halal bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CHANNEL_ID: ${{ secrets.HALAL_CHANNEL_ID }}
        run: |
          uv run halal_app.py
